
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

        
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenISalir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        ResistenciaP = new javax.swing.JMenuItem();
        ResistenciaS = new javax.swing.JMenuItem();
        Pitagoras = new javax.swing.JMenuItem();
        Acercade = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenISalir.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenISalir.add(jMenuItem1);

        jMenuBar1.add(MenISalir);

        jMenu9.setText("Modulos");

        ResistenciaP.setText("Resistencia en Paralelo");
        ResistenciaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResistenciaPActionPerformed(evt);
            }
        });
        jMenu9.add(ResistenciaP);

        ResistenciaS.setText("Resistencias en Serie");
        ResistenciaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResistenciaSActionPerformed(evt);
            }
        });
        jMenu9.add(ResistenciaS);

        Pitagoras.setText("Pitagoras");
        Pitagoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PitagorasActionPerformed(evt);
            }
        });
        jMenu9.add(Pitagoras);

        jMenuBar1.add(jMenu9);

        Acercade.setText("Acerca de");

        jMenuItem6.setText("Acerca de");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        Acercade.add(jMenuItem6);

        jMenuBar1.add(Acercade);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      System.exit(0);                                          

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ResistenciaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResistenciaSActionPerformed
  
        
        Resistencias_en_serie rs=new Resistencias_en_serie ();
       
       try {
       
       rs = new Resistencias_en_serie ();
       
       } 
       catch (Exception ex)
       {
        Logger.getLogger(Resistencias_en_serie.class.getName()).log(Level.SEVERE,null,ex);
       }
        rs.setLocationRelativeTo(null);
        rs.setVisible(true);
        this.setVisible(false);
        



        
        
    }//GEN-LAST:event_ResistenciaSActionPerformed

    private void ResistenciaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResistenciaPActionPerformed
      
        Resistencias_en_paralelo rp=new Resistencias_en_paralelo ();
       
       try {
       
       rp = new Resistencias_en_paralelo ();
       
       } 
       catch (Exception ex)
       {
        Logger.getLogger(Resistencias_en_paralelo.class.getName()).log(Level.SEVERE,null,ex);
       }
        rp.setLocationRelativeTo(null);
        rp.setVisible(true);
        this.setVisible(false);
                              
        
      
    
    
    
    }//GEN-LAST:event_ResistenciaPActionPerformed

    private void PitagorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PitagorasActionPerformed
                                                    
   
  Pitagoras pi=new Pitagoras ();
       
       try {
       
       pi = new Pitagoras ();
       
       } 
       catch (Exception ex)
       {
        Logger.getLogger(Pitagoras.class.getName()).log(Level.SEVERE,null,ex);
       }
        pi.setLocationRelativeTo(null);
        pi.setVisible(true);
        this.setVisible(false);

        
        
        
        
    }//GEN-LAST:event_PitagorasActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       
        Acerca_de acerca=new Acerca_de ();
       
       try {
       
       acerca = new Acerca_de ();
       
       } 
       catch (Exception ex)
       {
        Logger.getLogger(Acerca_de.class.getName()).log(Level.SEVERE,null,ex);
       }
        acerca.setLocationRelativeTo(null);
        acerca.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Acercade;
    private javax.swing.JMenu MenISalir;
    private javax.swing.JMenuItem Pitagoras;
    private javax.swing.JMenuItem ResistenciaP;
    private javax.swing.JMenuItem ResistenciaS;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
